apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
spec:
  rules:
  - host: 3.218.15.164
    http:
      paths:
      - backend:
          service:
            name: app
            port:
              number: 80
        path: /api
        pathType: Prefix
status:
  loadBalancer: {}
