apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
spec:
  rules:
    - host: 3.218.15.164
      http:
        paths:
          - path: /myapp
            pathType: Prefix
            backend:
              service:
                name: service
                port:
                  number: 80
